# Generated by Django 5.1.4 on 2024-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Укажите id в телеграм', max_length=100, null=True, verbose_name='Телеграм id'),
        ),
    ]
