# Generated by Django 5.1.4 on 2024-12-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название привычки', max_length=255, verbose_name='Название привычки')),
                ('action', models.TextField(blank=True, help_text='Укажите, что нужно сделать', null=True, verbose_name='Действие')),
                ('place', models.CharField(blank=True, help_text='Укажите, где нужно сделать действие', max_length=255, null=True, verbose_name='Место')),
                ('time', models.TimeField(auto_now=True, help_text='Укажите время для действия', null=True, verbose_name='Время')),
                ('is_pleasant', models.BooleanField(blank=True, default=False, help_text='Вознаградите себя за выполнение полезной привычки связанным действием', null=True, verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ежедневно'), (7, 'Еженедельно')], default=1, help_text='Укажите периодичность выполнения', null=True, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, help_text='Укажите вознаграждение за выполнение полезной привычки', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('estimated_time', models.PositiveSmallIntegerField(blank=True, default=120, help_text='Укажите время выполнения полезной привычки', null=True, verbose_name='Время на выполнение (секунды)')),
                ('is_public', models.BooleanField(blank=True, default=False, help_text='Укажите публичность привычки', null=True, verbose_name='Публичная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
