# Generated by Django 5.1.4 on 2024-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.CharField(blank=True, help_text='Укажите время для действия', max_length=30, null=True, verbose_name='Время'),
        ),
    ]
