# Generated by Django 5.1.4 on 2024-12-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_update_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='telegram_chat_id',
        ),
    ]
